### Ungrouped values, used to make GET-Parameters easier to write
### Values are assigned here only for debugging purposes
# Id of the event that the editor should open
mediaPackageId = '27cd7156-fda6-4b31-aab5-d56833012caf'

#### Values pertaining to accessing opencast
[opencast]
# URL of the opencast server on which we are editing events.
# Should be deleted when deployed in Opencast, as the editor can then
# figure out the correct URL by itself.
url = 'https://pyca.opencast.org'
# url = "http://localhost:8080"
# Opencast username. Used for Http basic authentication.
name = "admin"
# Password belonging to the above username
# WARNING: When run in Opencast, this file is publicly accessibly
password = "opencast"

### Settings of the metadata tab
[metadata]
# If false, the metadata button is not displayed in the main menu
show = true
## Here you can override various settings for how the metadata will be
## displayed in the editor, for each catalog.
## Setting #1: show (boolean)
## Whether the field should be visible at all
## Setting #2: readonly (boolean)
## Whether the field should be editable by the user
## If you don't configure a setting for a field, a default will be assumed.
## The default settings are based on the metadata display in the admin ui
## in Opencast, which can currently be configured in:
## org.opencastproject.ui.metadata.CatalogUIAdapterFactory-episode-common.cfg
## Furthermore:
## If a catalog is not specified, all fields of that catalog will be
## displayed.
## If a catalog is specified but empty, it will not be displayed at all.
## Example definition
# # This is the default catalog
# [metadata.configureFields."EVENTS.EVENTS.DETAILS.CATALOG.EPISODE"]
# title = {show = true, readonly = false}
# subject = {show = false}
# description = {readonly = true}

# # This catalog is specified but empty, and as such will not be displayed
# [metadata.configureFields."NameOfAnExtendedMetadataCatalog"]



### Settings of the thumbnail tab
[thumbnail]
# If false, the thumbnail tab is not displayed in the main menu
show = false