###
# Opencast Stand-alone Video Editor
##

# !!! When deployed, this file is publicly accessibly

###
# General Settings
##

# Id of the event that the editor should open by default.
# This is very useful as demo, but has no purpose otherwise.
# Type: string | undefined
# Default: undefined
mediaPackageId = '27cd7156-fda6-4b31-aab5-d56833012caf'


#### Values pertaining to accessing opencast
[opencast]

# URL of the opencast server to connect to.
# The default will work just fine if integrated in Opencast.
# Type: URL
# Default: Current server
url = 'https://pyca.opencast.org'

# Username, used for HTTP basic authentication against Opencast.
# Not defining this will work just fine if integrated in Opencast.
# Type: string | undefined
# Default: undefined
name = "admin"

# Username, used for HTTP basic authentication against Opencast.
# Not defining this will work just fine if integrated in Opencast.
# Type: string | undefined
# Default: undefined
password = "opencast"


### Settings of the metadata tab
[metadata]

# If the metadata editor appears in the main menu
# Type: boolean
# Default: true
#show = true

## Configure metadata display
## Here you can set which metadata fields should be displayed in the editor
## for each catalog.
## If the catalog is not specified, all fields of that catalog will be
## displayed.
## If the catalog is specified but empty, it will not be displayed at all.
## If the catalog is specified with at least one field, only the fields
## specified for the catalog will be displayed.
[metadata.showFields]

## Example definition
# # This is the default catalog
# "EVENTS.EVENTS.DETAILS.CATALOG.EPISODE" = [
#   "title",
#   "language",
#   "duration"
# ]
# "NameOfExtendedMetadataCatalog" = []


### Settings of the thumbnail tab
[thumbnail]

# If the thumbnail editor appears in the main menu
# Warning: This interface is unfinished
# Type: boolean
# Default: false
show = false
